baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Daniel Feldman'
theme = 'charter'

# Ignore content files inside the theme folder
ignoreFiles = ['themes/.*/content/.*']

relativeURLs = true
canonifyURLs = false
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Your blog description here"
  twitter = "https://twitter.com/d_feldman"
  bluesky = "https://bsky.app/profile/dfeldman.bsky.social"
  mastodon = "https://hachyderm.io/@dfeldman"
  email = "dfeldman.mn@gmail.com"
  calendly = "https://calendly.com/dfeldman"
  newsletter_signup_url = "https://your-newsletter-service.com/signup"
  author = "Your Name"
