name: default
type: default
llm: anthropic/claude-2.1
input_price: 8.0
output_price: 24.0
provider: anthropic
temperature: 0.7
expected_length: 3000
context_window: 4096
system_prompt: 'You are a professional writing assistant.

  Provide clear, detailed responses that directly address the task at hand.

  Focus on quality and completeness in your writing.'
